<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>test1</name>
   <tag></tag>
   <elementGuidId>87a9ff87-8f2c-4fe5-8011-5aac9cfcc887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;repo-content-pjax-container&quot;]/div/div/div[3]/div[1]/aside/div/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;repo-content-pjax-container&quot;]/div/div/div[3]/div[1]/aside/div/div[2]/div[2]/a</value>
      <webElementGuid>6ad08dc8-d094-4b10-b330-69b6c913bb3f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
